# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Differ < Formula
  desc "Terminal UI git diff viewer"
  homepage "https://github.com/dpuwork/differ"
  version "2.5.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dpuwork/differ/releases/download/v2.5.3/differ_darwin_amd64.tar.gz"
      sha256 "aa9b47c049e97809d0c9e3b18c938d9c282a4b28158f67a982c1cb2946a5dcc1"

      define_method(:install) do
        bin.install "differ"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dpuwork/differ/releases/download/v2.5.3/differ_darwin_arm64.tar.gz"
      sha256 "6b1d293074846bdb2c35faf13f4ce8056e4864a327dabf5cd0aad32ee5a1bb23"

      define_method(:install) do
        bin.install "differ"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dpuwork/differ/releases/download/v2.5.3/differ_linux_amd64.tar.gz"
      sha256 "3804d08f51309e29c1340d69d11e5caae1388b245c23a35943fc29683df1efde"
      define_method(:install) do
        bin.install "differ"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dpuwork/differ/releases/download/v2.5.3/differ_linux_arm64.tar.gz"
      sha256 "c917c0eecba4e565d751b699a5659e0f65ca96a385e2dfa5a960c01651680e76"
      define_method(:install) do
        bin.install "differ"
      end
    end
  end

  test do
    system "#{bin}/differ", "--version"
  end
end
