# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Differ < Formula
  desc "Terminal UI git diff viewer"
  homepage "https://github.com/dpuwork/differ"
  version "2.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dpuwork/differ/releases/download/v2.2.1/differ_darwin_amd64.tar.gz"
      sha256 "a6539a8380ce3daa198a316f01ca3d63d1d2e21097781ac74e678c203fa66694"

      define_method(:install) do
        bin.install "differ"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dpuwork/differ/releases/download/v2.2.1/differ_darwin_arm64.tar.gz"
      sha256 "afa9ab360ca58f0e72944eec37bfddaa79551ca3e501d23ee83d3ad88bdb4ec0"

      define_method(:install) do
        bin.install "differ"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dpuwork/differ/releases/download/v2.2.1/differ_linux_amd64.tar.gz"
      sha256 "2eb19018641af56851fefbf25f053fda055fdf91c90ead508002ced4bf4a24f0"
      define_method(:install) do
        bin.install "differ"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dpuwork/differ/releases/download/v2.2.1/differ_linux_arm64.tar.gz"
      sha256 "3f0e29b0ec84b6b71729fb091b88818e684435c090021d0d270dcbf24b195b39"
      define_method(:install) do
        bin.install "differ"
      end
    end
  end

  test do
    system "#{bin}/differ", "--version"
  end
end
