# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dumb < Formula
  desc "tmux dumb - a layout helper for tmux"
  homepage "https://github.com/dpuwork/dumb"
  version "0.1.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dpuwork/dumb/releases/download/v0.1.6/dumb_v0.1.6_darwin_amd64.tar.gz"
      sha256 "2c0bbd90cd3bc5466f1d354cf02d53a286fc327ac14b724d6c7236e3b06d07ff"

      define_method(:install) do
        bin.install "bin/dumb" => "dumb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dpuwork/dumb/releases/download/v0.1.6/dumb_v0.1.6_darwin_arm64.tar.gz"
      sha256 "3cebce9a416e70380954821dcd8909623dfca2a7730780188cfca4f34282359c"

      define_method(:install) do
        bin.install "bin/dumb" => "dumb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dpuwork/dumb/releases/download/v0.1.6/dumb_v0.1.6_linux_amd64.tar.gz"
      sha256 "cc2a05f39bc9629b477695f72f8201fcd860a0e698eef6d8edc6ca0dda6158bd"
      define_method(:install) do
        bin.install "bin/dumb" => "dumb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dpuwork/dumb/releases/download/v0.1.6/dumb_v0.1.6_linux_arm64.tar.gz"
      sha256 "1c3d788b2719fd7547b0f915ae3cf8740e74364e85008db0b283a3438f405f1e"
      define_method(:install) do
        bin.install "bin/dumb" => "dumb"
      end
    end
  end
end
