# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dumb < Formula
  desc "tmux dumb - a layout helper for tmux"
  homepage "https://github.com/dpuwork/dumb"
  version "0.1.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dpuwork/dumb/releases/download/v0.1.8/dumb_v0.1.8_darwin_amd64.tar.gz"
      sha256 "6b0767ecc0b34ba4bd3b458a368e1f1e4da14d24e1d6c6449770b1b960b6057a"

      define_method(:install) do
        bin.install "dumb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dpuwork/dumb/releases/download/v0.1.8/dumb_v0.1.8_darwin_arm64.tar.gz"
      sha256 "7d398848dcb203ecb52fb6a0c43fe65030165232367b8cd5a074f2a61c491f71"

      define_method(:install) do
        bin.install "dumb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dpuwork/dumb/releases/download/v0.1.8/dumb_v0.1.8_linux_amd64.tar.gz"
      sha256 "645d6cec5c8d45b4061c5c07069bf49cc2a1361ce53c93b130d7cd65b22e1a50"
      define_method(:install) do
        bin.install "dumb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dpuwork/dumb/releases/download/v0.1.8/dumb_v0.1.8_linux_arm64.tar.gz"
      sha256 "1b27f03ce0737ecf31aac670b51a97d1082c898b6fd0f66cd91d3df884de21cd"
      define_method(:install) do
        bin.install "dumb"
      end
    end
  end
end
