# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dumb < Formula
  desc "tmux dumb - a layout helper for tmux"
  homepage "https://github.com/dpuwork/dumb"
  version "0.1.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dpuwork/dumb/releases/download/v0.1.7/dumb_v0.1.7_darwin_amd64.tar.gz"
      sha256 "146988846f52848eddda4da6c15e4bb341b6d64f55af966578cdc0167b7217e6"

      define_method(:install) do
        bin.install "dumb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dpuwork/dumb/releases/download/v0.1.7/dumb_v0.1.7_darwin_arm64.tar.gz"
      sha256 "7511bee590bbd85468fe5b9611963ec25ff30fd404599e31a7a186dd48c7919e"

      define_method(:install) do
        bin.install "dumb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dpuwork/dumb/releases/download/v0.1.7/dumb_v0.1.7_linux_amd64.tar.gz"
      sha256 "8c1f7e30038570d30710fef3b0d763dfb689a27c5d49ecebe4720dd94ab53bd5"
      define_method(:install) do
        bin.install "dumb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dpuwork/dumb/releases/download/v0.1.7/dumb_v0.1.7_linux_arm64.tar.gz"
      sha256 "716d96f35fcb52ef189384ef6c2e1aec0cb84431780fcc3b2cf227df797ad175"
      define_method(:install) do
        bin.install "dumb"
      end
    end
  end
end
